/*
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module EnergyStorageModule {

  @topic
  struct EsmSignal {
    string power_interface;
    //string control_word;
    @key long signal_id;
    //string status;
	long terminal_voltage;
    long count;
	//long terminal_current;
	//long state_of_charge;
  };
};
