/* Derived from section 5.4.1 in MDD */

module EnergyStorageModule
{
	@topic
	struct FeedbackSignals
	{
		@key string name;
		float signal_1;
		float signal_2;
		float signal_3;
		float signal_4;
		float signal_5;
		float signal_6;
		float signal_7;
		float signal_8;
		float signal_9;
		float signal_10;
	};
};
