/*
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module EnergyStorageModule {

  @topic
  struct EsmSignals {
	@key string power_interface;
	boolean control_word;
	boolean device_status;
	float terminal_voltage;
	string voltage_unit;
	float terminal_current;
	string current_unit;
	long state_of_charge;
	string soc_unit;
	long timestamp;
  };
};
