/*
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module EnergyStorageModule {

  @topic
  struct EsmSignal {
	@key string power_interface;
	string control_word;
	string status;
	float terminal_voltage;
	string voltage_unit;
	float terminal_current;
	string current_unit;
	long state_of_charge;
	string soc_unit;
	string timestamp;
  };
};
