/*
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

module ToEnergyStorageModule {

  @topic
  struct ToEsmSignal {
	@key string power_interface;
	string control_word;
	string timestamp;
  };
};
